### ISSUE TITLE
Publish armv7l architecture images

### ISSUE THREAD

**Issue by dzek69** [astefanutti/scratch-node#1]
Hello,
I'd love to see armv7l images published to docker hub.
Current images cannot be run on Raspberry Pi for example.

**Comment by dzek69** [comment]
Looks like `node-musl` isn't compatible with arm anyway :(

```
Step 7/16 : RUN npm install --no-save node-musl
 ---> Running in 9de1eb17d845
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for node-musl@0.0.6: wanted {"os":"linux","arch":"x64,ia32"} (current: {"os":"linux","arch":"arm"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm
```

I'm not much into building stuff from sources, so I have no idea if this can be worked around.

**Comment by astefanutti** [comment]
Yes, I think it should work and may just be a matter of adding `arm` to node-musl `package.json` file. I'll have a look ASAP.

**Comment by astefanutti** [comment]
I've been able to cross-compile binary for `armv7l`. I still need to polish things and create the Docker manifest for multi-arch images.

**Comment by astefanutti** [comment]
The `latest`, `12`, `12.2`, `12.2.0` tags now provide multi-architecture images for `amd64`, `arm32v6`, `arm32v7` and `arm64v8`.

**Comment by dzek69** [comment]
Thank you!
