### ISSUE TITLE
Not working with flatstr. "SyntaxError: Unexpected token %"

### ISSUE THREAD

**Issue by FedericoBiccheddu** [astefanutti/scratch-node#4]
I think the problem is caused by the flag `--allow-natives-syntax` used here: https://github.com/davidmarkclements/flatstr/blob/1b63eebba9e88c7d21d1643055e22aa830b3e12b/index.js

Sadly, I have no idea what to do to help with this issue.

Node v12.1.0
flatstr v1.0.9

**Comment by astefanutti** [comment]
Apparently, there have been a couple of fixes for Node 12 required:

https://github.com/davidmarkclements/flatstr/commit/689e327f8ad82f4d9c017185fb064f791beecf0a
https://github.com/davidmarkclements/flatstr/commit/4306e6586453d4d76b3aae309a484be70e7e62d5

It may help to upgrade flatstr to version 1.0.11.

**Comment by FedericoBiccheddu** [comment]
Thank you, the last commit seems to fix the problem.
